pmaweb/templates/_sponsorship_conditions.html

As agreed on the team meeting, see
https://irc.phpmyadmin.net/meetbot/phpmyadmin/2016/phpmyadmin.2016-11-09-12.16.html

Document not acceptable sites

---

pmaweb/settings.py

No longer offer 4.4 for download

---

pmaweb/templates/themes.html

Document support status of themes

---

pmaweb/templates/downloads.html

See https://github.com/phpmyadmin/phpmyadmin/issues/12821

Improve daily snapshot download link

---

pmaweb/templates/_sponsorship_conditions.html

Hopefully this will set correct expectations for sponsors.

Document sponsorship process

---

pmaweb/templates/license.html

- upgrade to current CC
- remove the share alike condition as it makes it hard to include
thinkgs like screenshots in third part materials

Change website content license to CC BY 4.0

---

pmaweb/templates/_sponsorship_conditions.html

We already enforce it like this since beginning (to avoid being seen as
advertisement which we can not sell to honor non profit status).

Clarify text conditions

---

pmaweb/templates/base.html

Signed-off-by: Marc Delisle <marc@infomarc.info>

Fix typos, improve wording

---

pmaweb/templates/team.html

Add DebConf17 description

---

pmaweb/templates/team.html

Signed-off-by: Marc Delisle <marc@infomarc.info>

Reorganize the team's description

---

pmaweb/templates/index.html

Signed-off-by: Marc Delisle <marc@infomarc.info>

Avoid the need of a yearly update

---

pmaweb/templates/_sponsorship_conditions.html

This reverts commit f6a7ff33e7b805468480c40c69beebee98d5cb79.

Revert "Increase price for Gold level as agreed on the team meeting"

---

pmaweb/templates/_sponsorship_conditions.html

The most frequent request we get at donate@phpmyadmin.net is about discounts, hopefully this will make it clearer that there are none.

Clarify that there are no discounts

---

README.rst
pmaweb/fixtures/test_data.json
pmaweb/templates/security/rss.html

- Fixed CVE links #73 
- Added test data
- Added migrate command to README

Fix CVE links & update README

---

pmaweb/templates/sponsors.html

Signed-off-by: Marc Delisle <marc@infomarc.info>

Improve English

---

.well-known/security.txt

Based on https://securitytxt.org/ standard.

Create .well-known/security.txt file

---

pmaweb/templates/_sponsorship_conditions.html

Bradley suggested that we explicitly state this, the phrasing comes directly from him. See also SFC ticket number 5897.

Explicitly note that sponsorships are not refundable

---

pmaweb/templates/_sponsors.html
pmaweb/templates/sponsors.html

Related to https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

Update sponsored links relationship attribute

---

pmaweb/templates/downloads.html

Improve end of life (EOL) and long-term support (LTS) grid

---

pmaweb/settings.py

Fixes https://github.com/phpmyadmin/website/issues/97

List newest download first

---

demo/models.py
pmaweb/templates/_list-demos.html

Direct logins does not work since 4.9.

Remove direct logins in the demo list

---

files/models.py

Explicitly list MariaDB support in the download description
